OK
OK
Loading data to table encrypt_db4data.table001
3 Rows loaded to encrypt_db4data.table001
OK
OK
Loading data to table encrypt_db4data.table_tgt
Moved: 'viewfs://hadoop-meituan-test/user/hive/warehouse/encrypt_db4data.db/table_tgt' to trash at: hdfs://hadoop-meituan-test/user/hdp_qa/.Trash/Current
1 Rows loaded to encrypt_db4data.table_tgt
OK
name	ip
OK
row_count
1
FAILED: SemanticException Column insufficient privileges to access: <encrypt_db4data>.<table_tgt>.<name>
Loading data to table encrypt_db4data.table_tgt
Moved: 'viewfs://hadoop-meituan-test/user/hive/warehouse/encrypt_db4data.db/table_tgt' to trash at: hdfs://hadoop-meituan-test/user/hdp_qa/.Trash/Current
3 Rows loaded to encrypt_db4data.table_tgt
OK
table001.name	table001.ip
OK
row_count
3
FAILED: SemanticException Column insufficient privileges to access: <encrypt_db4data>.<table_tgt>.<name>
FAILED: SemanticException [Error 10004]: Line 3:63 Invalid table alias or column reference 'name': (possible column names are: table_tgt.encrypted_name_84382_name, table_tgt.ip) or Column insufficient privileges to access: name
OK
OK
